# Generated by Django 3.0.3 on 2020-03-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Gezi',
        ),
    ]
