# Generated by Django 3.0.3 on 2020-03-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200324_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gezi',
            new_name='Activity',
        ),
    ]
