# Generated by Django 3.0.3 on 2020-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200324_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='person_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
