# Generated by Django 3.0.3 on 2020-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_activity_person_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='person_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
