# Generated by Django 3.0.3 on 2020-03-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='trip',
        ),
    ]
