# Generated by Django 3.0.3 on 2020-03-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200326_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='imaget',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
