# Generated by Django 3.0.3 on 2020-03-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_trip_imaget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageTrip',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='imaget',
            new_name='image',
        ),
    ]
