# Generated by Django 3.0.3 on 2020-04-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200416_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Product',
        ),
    ]
