# Generated by Django 3.0.3 on 2020-04-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetrip',
            old_name='trip',
            new_name='product',
        ),
    ]
