# Generated by Django 3.0.3 on 2020-04-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200424_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTrip',
            new_name='Images',
        ),
    ]
