# Generated by Django 3.0.3 on 2020-04-25 10:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200425_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shortDetail',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
