# Generated by Django 3.0.3 on 2020-05-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20200515_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Menu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Activity', 'Activity'), ('Menu', 'Menu')], default='Category', max_length=10),
        ),
    ]
