# Generated by Django 3.0.3 on 2020-05-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20200519_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
