# Generated by Django 3.0.3 on 2020-05-23 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20200520_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='content',
        ),
    ]
