# Generated by Django 3.0.3 on 2020-05-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20200523_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment_num',
            field=models.IntegerField(null=True),
        ),
    ]
